-- ============================================================
-- TIPL Fantasy Cricket — Consolidated Schema
-- Generated by merging migrations 001-028 (excluding stripped features)
-- ============================================================

-- ============================================================
-- CUSTOM TYPES
-- ============================================================
CREATE TYPE player_role AS ENUM ('WK', 'BAT', 'AR', 'BOWL');
CREATE TYPE match_status AS ENUM ('upcoming', 'live', 'completed', 'no_result', 'abandoned');
CREATE TYPE scoring_category AS ENUM ('batting', 'bowling', 'fielding', 'bonus', 'penalty');
CREATE TYPE notification_type AS ENUM ('match_reminder', 'scores_published', 'admin', 'system');

-- ============================================================
-- PROFILES (linked to auth.users)
-- ============================================================
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name TEXT NOT NULL DEFAULT '',
  avatar_url TEXT,
  is_admin BOOLEAN NOT NULL DEFAULT false,
  auto_pick_enabled BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON COLUMN profiles.auto_pick_enabled IS 'If true, system auto-picks team within 2 min of match deadline if user has no selection.';

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name, avatar_url, is_admin, created_at, updated_at)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    COALESCE(NEW.raw_user_meta_data->>'avatar_url', NEW.raw_user_meta_data->>'picture'),
    false,
    NOW(),
    NOW()
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- ============================================================
-- TEAMS
-- ============================================================
CREATE TABLE teams (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  short_name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#888888',
  logo_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- PLAYERS
-- ============================================================
CREATE TABLE players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  team_id UUID NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  role player_role NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  cricapi_id TEXT,
  credit_cost NUMERIC(3,1) NOT NULL DEFAULT 7.0,
  image_url TEXT,
  -- Howstat integration
  howstat_id INTEGER,
  stats_updated_at TIMESTAMPTZ,
  -- Batting stats
  ipl_matches INTEGER,
  ipl_innings INTEGER,
  ipl_runs INTEGER,
  ipl_batting_avg NUMERIC,
  ipl_strike_rate NUMERIC,
  ipl_highest_score TEXT,
  ipl_fifties INTEGER,
  ipl_hundreds INTEGER,
  ipl_fours INTEGER,
  ipl_sixes INTEGER,
  -- Bowling stats
  ipl_wickets INTEGER,
  ipl_bowling_avg NUMERIC,
  ipl_economy NUMERIC,
  ipl_best_bowling TEXT,
  -- Fielding
  ipl_catches INTEGER,
  -- Recent form (last 5 IPL innings scores)
  ipl_recent_scores INTEGER[],
  -- Form indicator for quick display
  form_indicator TEXT DEFAULT 'neutral',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_players_team ON players(team_id);
CREATE INDEX idx_players_role ON players(role);

-- ============================================================
-- MATCHES
-- ============================================================
CREATE TABLE matches (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  match_number INTEGER NOT NULL UNIQUE,
  team_home_id UUID NOT NULL REFERENCES teams(id),
  team_away_id UUID NOT NULL REFERENCES teams(id),
  venue TEXT NOT NULL DEFAULT '',
  start_time TIMESTAMPTZ NOT NULL,
  status match_status NOT NULL DEFAULT 'upcoming',
  cricapi_match_id TEXT,
  result_summary TEXT,
  live_scores_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_matches_status ON matches(status);
CREATE INDEX idx_matches_start ON matches(start_time);

-- ============================================================
-- PLAYING_XI
-- ============================================================
CREATE TABLE playing_xi (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  team_id UUID NOT NULL REFERENCES teams(id),
  announced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(match_id, player_id)
);

-- ============================================================
-- SELECTIONS
-- ============================================================
CREATE TABLE selections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  captain_id UUID REFERENCES players(id),
  vice_captain_id UUID REFERENCES players(id),
  is_auto_pick BOOLEAN NOT NULL DEFAULT false,
  locked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, match_id)
);

CREATE INDEX idx_selections_match ON selections(match_id);
CREATE INDEX idx_selections_user ON selections(user_id);

-- ============================================================
-- SELECTION_PLAYERS (join table)
-- ============================================================
CREATE TABLE selection_players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  selection_id UUID NOT NULL REFERENCES selections(id) ON DELETE CASCADE,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  UNIQUE(selection_id, player_id)
);

CREATE INDEX idx_selection_players_selection ON selection_players(selection_id);

-- ============================================================
-- SCORING_RULES
-- ============================================================
CREATE TABLE scoring_rules (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  category scoring_category NOT NULL,
  name TEXT NOT NULL UNIQUE,
  label TEXT NOT NULL,
  points NUMERIC NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- MATCH_PLAYER_SCORES
-- ============================================================
CREATE TABLE match_player_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  runs INTEGER NOT NULL DEFAULT 0,
  balls_faced INTEGER NOT NULL DEFAULT 0,
  fours INTEGER NOT NULL DEFAULT 0,
  sixes INTEGER NOT NULL DEFAULT 0,
  wickets INTEGER NOT NULL DEFAULT 0,
  overs_bowled NUMERIC NOT NULL DEFAULT 0,
  runs_conceded INTEGER NOT NULL DEFAULT 0,
  maidens INTEGER NOT NULL DEFAULT 0,
  catches INTEGER NOT NULL DEFAULT 0,
  stumpings INTEGER NOT NULL DEFAULT 0,
  run_outs INTEGER NOT NULL DEFAULT 0,
  fantasy_points NUMERIC NOT NULL DEFAULT 0,
  breakdown JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(match_id, player_id)
);

-- ============================================================
-- USER_MATCH_SCORES
-- ============================================================
CREATE TABLE user_match_scores (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  match_id UUID NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  total_points NUMERIC NOT NULL DEFAULT 0,
  rank INTEGER,
  captain_points NUMERIC NOT NULL DEFAULT 0,
  vc_points NUMERIC NOT NULL DEFAULT 0,
  breakdown JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(user_id, match_id)
);

CREATE INDEX idx_ums_user ON user_match_scores(user_id);
CREATE INDEX idx_ums_match_user ON user_match_scores(match_id, user_id);

-- ============================================================
-- ADMIN_LOGS
-- ============================================================
CREATE TABLE admin_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id UUID NOT NULL REFERENCES profiles(id),
  action TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT,
  details JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================
CREATE TABLE notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL DEFAULT '',
  type notification_type NOT NULL DEFAULT 'system',
  is_read BOOLEAN NOT NULL DEFAULT false,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_notifications_user ON notifications(user_id);

-- ============================================================
-- PLAYER STATS TABLES (season / venue / vs-team breakdowns)
-- ============================================================

CREATE TABLE player_season_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  season INTEGER NOT NULL,
  matches INTEGER DEFAULT 0,
  innings INTEGER DEFAULT 0,
  runs INTEGER DEFAULT 0,
  balls_faced INTEGER DEFAULT 0,
  fours INTEGER DEFAULT 0,
  sixes INTEGER DEFAULT 0,
  highest_score INTEGER DEFAULT 0,
  fifties INTEGER DEFAULT 0,
  hundreds INTEGER DEFAULT 0,
  not_outs INTEGER DEFAULT 0,
  overs_bowled NUMERIC DEFAULT 0,
  runs_conceded INTEGER DEFAULT 0,
  wickets INTEGER DEFAULT 0,
  maidens INTEGER DEFAULT 0,
  catches INTEGER DEFAULT 0,
  stumpings INTEGER DEFAULT 0,
  run_outs INTEGER DEFAULT 0,
  UNIQUE(player_id, season)
);
CREATE INDEX idx_pss_player_season ON player_season_stats(player_id, season DESC);

CREATE TABLE player_venue_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  venue TEXT NOT NULL,
  matches INTEGER DEFAULT 0,
  runs INTEGER DEFAULT 0,
  balls_faced INTEGER DEFAULT 0,
  wickets INTEGER DEFAULT 0,
  overs_bowled NUMERIC DEFAULT 0,
  runs_conceded INTEGER DEFAULT 0,
  UNIQUE(player_id, venue)
);
CREATE INDEX idx_pvs_player ON player_venue_stats(player_id);

CREATE TABLE player_vs_team_stats (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id UUID NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  opponent_team TEXT NOT NULL,
  matches INTEGER DEFAULT 0,
  runs INTEGER DEFAULT 0,
  balls_faced INTEGER DEFAULT 0,
  wickets INTEGER DEFAULT 0,
  overs_bowled NUMERIC DEFAULT 0,
  runs_conceded INTEGER DEFAULT 0,
  UNIQUE(player_id, opponent_team)
);
CREATE INDEX idx_pvt_player ON player_vs_team_stats(player_id);

-- ============================================================
-- SEASON_LEADERBOARD (materialized view)
-- ============================================================
CREATE MATERIALIZED VIEW season_leaderboard AS
SELECT
  p.id AS user_id,
  p.display_name,
  p.avatar_url,
  COALESCE(SUM(ums.total_points), 0) AS total_points,
  COUNT(ums.id) AS matches_played,
  CASE WHEN COUNT(ums.id) > 0
    THEN ROUND(SUM(ums.total_points) / COUNT(ums.id), 1)
    ELSE 0
  END AS avg_points,
  COUNT(CASE WHEN ums.rank = 1 THEN 1 END) AS first_place_count,
  COUNT(CASE WHEN ums.rank <= 3 THEN 1 END) AS podium_count,
  ROW_NUMBER() OVER (ORDER BY COALESCE(SUM(ums.total_points), 0) DESC) AS season_rank
FROM profiles p
LEFT JOIN user_match_scores ums ON ums.user_id = p.id
GROUP BY p.id, p.display_name, p.avatar_url;

CREATE UNIQUE INDEX idx_leaderboard_user ON season_leaderboard(user_id);

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Refresh the leaderboard materialized view
CREATE OR REPLACE FUNCTION refresh_leaderboard()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY season_leaderboard;
END;
$$;

-- Auto-lock upcoming matches when start_time has passed
CREATE OR REPLACE FUNCTION public.auto_lock_matches()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  UPDATE matches
  SET status = 'live', updated_at = NOW()
  WHERE status = 'upcoming'
    AND start_time <= NOW();
END;
$$;

-- Award standings (purple cap, orange cap, mvp)
CREATE OR REPLACE FUNCTION get_award_standings(p_category TEXT, p_limit INTEGER DEFAULT 10)
RETURNS TABLE (
  player_id UUID,
  player_name TEXT,
  team_short_name TEXT,
  team_color TEXT,
  stat_value NUMERIC,
  matches_played BIGINT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  IF p_category = 'purple_cap' THEN
    RETURN QUERY
      SELECT
        mps.player_id,
        p.name AS player_name,
        t.short_name AS team_short_name,
        t.color AS team_color,
        SUM(mps.wickets)::NUMERIC AS stat_value,
        COUNT(DISTINCT mps.match_id) AS matches_played
      FROM match_player_scores mps
      JOIN players p ON p.id = mps.player_id
      JOIN teams t ON t.id = p.team_id
      GROUP BY mps.player_id, p.name, t.short_name, t.color
      HAVING SUM(mps.wickets) > 0
      ORDER BY stat_value DESC
      LIMIT p_limit;

  ELSIF p_category = 'orange_cap' THEN
    RETURN QUERY
      SELECT
        mps.player_id,
        p.name AS player_name,
        t.short_name AS team_short_name,
        t.color AS team_color,
        SUM(mps.runs)::NUMERIC AS stat_value,
        COUNT(DISTINCT mps.match_id) AS matches_played
      FROM match_player_scores mps
      JOIN players p ON p.id = mps.player_id
      JOIN teams t ON t.id = p.team_id
      GROUP BY mps.player_id, p.name, t.short_name, t.color
      HAVING SUM(mps.runs) > 0
      ORDER BY stat_value DESC
      LIMIT p_limit;

  ELSIF p_category = 'mvp' THEN
    RETURN QUERY
      SELECT
        mps.player_id,
        p.name AS player_name,
        t.short_name AS team_short_name,
        t.color AS team_color,
        SUM(mps.fantasy_points)::NUMERIC AS stat_value,
        COUNT(DISTINCT mps.match_id) AS matches_played
      FROM match_player_scores mps
      JOIN players p ON p.id = mps.player_id
      JOIN teams t ON t.id = p.team_id
      GROUP BY mps.player_id, p.name, t.short_name, t.color
      HAVING SUM(mps.fantasy_points) > 0
      ORDER BY stat_value DESC
      LIMIT p_limit;
  END IF;
END;
$$;

-- Initial refresh of leaderboard
REFRESH MATERIALIZED VIEW season_leaderboard;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE playing_xi ENABLE ROW LEVEL SECURITY;
ALTER TABLE selections ENABLE ROW LEVEL SECURITY;
ALTER TABLE selection_players ENABLE ROW LEVEL SECURITY;
ALTER TABLE scoring_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE match_player_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_match_scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_season_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_venue_stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_vs_team_stats ENABLE ROW LEVEL SECURITY;

-- PROFILES
CREATE POLICY "profiles_select_all" ON profiles
  FOR SELECT USING (true);
CREATE POLICY "profiles_update_own" ON profiles
  FOR UPDATE USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- TEAMS
CREATE POLICY "teams_select_all" ON teams
  FOR SELECT TO authenticated USING (true);

-- PLAYERS
CREATE POLICY "players_select_all" ON players
  FOR SELECT TO authenticated USING (true);

-- MATCHES
CREATE POLICY "matches_select_all" ON matches
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "matches_update_admin" ON matches
  FOR UPDATE TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true));

-- PLAYING_XI
CREATE POLICY "playing_xi_select_all" ON playing_xi
  FOR SELECT TO authenticated USING (true);

-- SELECTIONS
CREATE POLICY "selections_select" ON selections
  FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM matches
      WHERE matches.id = selections.match_id
      AND matches.status IN ('live', 'completed', 'no_result')
    )
  );
CREATE POLICY "selections_insert_own" ON selections
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM matches
      WHERE matches.id = match_id
      AND matches.status = 'upcoming'
      AND matches.start_time > NOW()
    )
  );
CREATE POLICY "selections_update_own" ON selections
  FOR UPDATE TO authenticated
  USING (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM matches
      WHERE matches.id = selections.match_id
      AND matches.status = 'upcoming'
      AND matches.start_time > NOW()
    )
  )
  WITH CHECK (user_id = auth.uid());
CREATE POLICY "selections_delete_own" ON selections
  FOR DELETE TO authenticated
  USING (
    user_id = auth.uid()
    AND EXISTS (
      SELECT 1 FROM matches
      WHERE matches.id = selections.match_id
      AND matches.status = 'upcoming'
    )
  );

-- SELECTION_PLAYERS
CREATE POLICY "selection_players_select" ON selection_players
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM selections s
      WHERE s.id = selection_players.selection_id
      AND (
        s.user_id = auth.uid()
        OR EXISTS (
          SELECT 1 FROM matches m
          WHERE m.id = s.match_id
          AND m.status IN ('live', 'completed', 'no_result')
        )
      )
    )
  );
CREATE POLICY "selection_players_insert_own" ON selection_players
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM selections s
      WHERE s.id = selection_players.selection_id
      AND s.user_id = auth.uid()
    )
  );
CREATE POLICY "selection_players_delete_own" ON selection_players
  FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM selections s
      WHERE s.id = selection_players.selection_id
      AND s.user_id = auth.uid()
    )
  );

-- SCORING_RULES
CREATE POLICY "scoring_rules_select_all" ON scoring_rules
  FOR SELECT TO authenticated USING (true);

-- MATCH_PLAYER_SCORES
CREATE POLICY "match_player_scores_select" ON match_player_scores
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM matches
      WHERE matches.id = match_player_scores.match_id
      AND matches.status IN ('completed', 'no_result')
    )
  );

-- USER_MATCH_SCORES
CREATE POLICY "user_match_scores_select" ON user_match_scores
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM matches
      WHERE matches.id = user_match_scores.match_id
      AND matches.status IN ('completed', 'no_result')
    )
  );

-- ADMIN_LOGS
CREATE POLICY "admin_logs_select_admin" ON admin_logs
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true));
CREATE POLICY "admin_logs_insert_admin" ON admin_logs
  FOR INSERT TO authenticated
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND is_admin = true));

-- NOTIFICATIONS
CREATE POLICY "notifications_select_own" ON notifications
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());
CREATE POLICY "notifications_update_own" ON notifications
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- PLAYER STATS TABLES
CREATE POLICY "Anyone can read season stats" ON player_season_stats
  FOR SELECT USING (true);
CREATE POLICY "Anyone can read venue stats" ON player_venue_stats
  FOR SELECT USING (true);
CREATE POLICY "Anyone can read vs-team stats" ON player_vs_team_stats
  FOR SELECT USING (true);
